# Generated by Django 2.2.3 on 2019-10-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.TimeField(verbose_name='HH:MM'),
        ),
    ]
