# Generated by Django 2.2.3 on 2019-10-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20191014_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.TimeField(),
        ),
    ]
