# Generated by Django 2.2.3 on 2019-10-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20191014_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='if_private',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
