# Generated by Django 2.2.3 on 2019-11-18 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
