# Generated by Django 2.2.3 on 2019-10-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
